pento_app/urls.py
from django.urls import path
from . import views
from .admin import mypage_site

app_name = 'pento_app'

urlpatterns = [
    path('mypage/', mypage_site.urls, name='mypage'),
    path('', views.index, name='index'),
    path('<slug:username>/edit', views.edit, name='edit'),
    path('create/', views.create, name='create'),
    path('<slug:username>', views.detail, name='detail'),
    path('delete/<int:pk>', views.delete, name='delete'), 
    path('<str:username>/delete/', views.userdelete, name='userdelete'),
    path('like/', views.like, name='like'),
    path('settings/', views.settings, name='settings'),
    path('<slug:username>/follow', views.follow_view, name='follow'),
    path('<slug:username>/unfollow', views.unfollow_view, name='unfollow'),
]

pento_arts/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth.models import Group

admin.site.site_title = '管理サイト（管理者用）'
admin.site.site_header = '管理サイト（管理者用）'
admin.site.index_title = 'メニュー'

app_name = 'pento_app'

urlpatterns = [
    path('staff-admin/', admin.site.urls),
    path('', include("pento_app.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/email/', RedirectView.as_view(pattern_name='pento_app:index')),
    path('accounts/inactive/', RedirectView.as_view(pattern_name='pento_app:index')),
    path('accounts/password/change/', RedirectView.as_view(pattern_name='pento_app:index')),
    path('accounts/confirm-email/', RedirectView.as_view(pattern_name='pento_app:index')),
    re_path(r'^accounts/confirm-email/[^/]+/', RedirectView.as_view(pattern_name='pento_app:index'), kwargs=None),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pento_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit
from django.utils import timezone
from django.urls import reverse

#ユーザーモデル（公開ユーザー情報用にカスタマイズ）
class CustomUser(AbstractUser):
    description = models.TextField(verbose_name='プロフィール', null=True, blank=True)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True, upload_to='images/')
    thumbnail = ImageSpecField(source='photo', processors=[ResizeToFill(256,256)], format='JPEG', options={'quality': 60})
    email = models.EmailField('メールアドレス', unique = True)

    def get_absolute_url(self):
        return reverse('pento_app:detail', kwargs={'username': self.username})

    class Meta:
        verbose_name_plural = 'CustomUser'

#タイムラインモデル
class Post(models.Model):
    author = models.ForeignKey('pento_app.CustomUser', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='本文')
    photo = models.ImageField(verbose_name='写真', blank=True, null=True, upload_to='images/')
    post_photo = ImageSpecField(source='photo', processors=[ResizeToFit(1080,1080)], format='JPEG', options={'quality': 60})
    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    def get_like(self):
        likes = Like.objects.filter(post=self)
        return [like.user for like in likes]

#『いいね』モデル
class Like(models.Model):
    user = models.ForeignKey('pento_app.CustomUser', on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    #ユーザーが重複して『いいね』を押せないよう設定する
    class Meta:
        unique_together = ('user', 'post')

#フォローモデル
class Connection(models.Model):
    follower = models.ForeignKey(CustomUser, related_name='follower', on_delete=models.CASCADE)
    following = models.ForeignKey(CustomUser, related_name='following', on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} : {}".format(self.follower.username, self.following.username)

pento_app/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import CustomUser
from .models import Post

User = get_user_model()

#プロフィール編集
class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = CustomUser
        fields = ('username','description')
        help_texts = {
            'username': None,
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text',)

pento_app/views.py
from __future__ import absolute_import
from django.conf import settings

from django.core.checks import messages
from django.contrib import messages
from django.views import generic
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin 
from django.contrib.messages.views import SuccessMessageMixin

from .models import CustomUser, Post, Like, Connection
from .forms import ProfileForm, PostForm
from .helpers import get_current_user

User = get_user_model()

"""------------------タイムライン------------------------------------------------------------"""
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'index.html'
    paginate_by = 10

    def get_queryset(self):
        posts = Post.objects.order_by('-created_at')
        return posts

"""------------------ツイート投稿------------------------------------------------------------"""
class CreateView(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    success_url = reverse_lazy('pento_app:index')

    #投稿成功時の処理
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        messages.success(self.request, '投稿が完了しました。')
        return super(CreateView, self).form_valid(form)

    #投稿失敗時の処理
    def form_invalid(self, form):
        if form:
            messages.warning(self.request, '空白では投稿できません！')
            return redirect('pento_app:index')
        else:
            messages.warning(self.request, '投稿が失敗しました。')
            return redirect('pento_app:index')

"""------------------プロフィール画面------------------------------------------------------------"""
class ProifileDetail(LoginRequiredMixin, generic.DetailView):
    model = CustomUser
    template_name = 'detail.html'

    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(ProifileDetail, self).get_context_data(**kwargs)
        username = self.kwargs['username']
        context['username'] = username
        context['user'] = get_current_user(self.request)
        context['following'] = Connection.objects.filter(follower__username=username).count()
        context['follower'] = Connection.objects.filter(following__username=username).count()

        if username is not context['user'].username:
            result = Connection.objects.filter(follower__username=context['user'].username).filter(following__username=username)
            context['connected'] = True if result else False

        return context

"""------------------プロフィール編集ページ------------------------------------------------------"""
class ProfileEdit(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = CustomUser
    form_class = ProfileForm
    template_name = 'edit.html'
    success_url = 'edit'
    success_message = 'プロフィールを更新しました。'

    def get_object(self):
        return self.request.user

"""------------------投稿削除--------------------------------------------------------------------"""
class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('pento_app:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == request.user:
            messages.success(self.request, '削除しました。')
            return super().delete(request, *args, **kwargs)

"""------------------『いいね』機能---------------------------------------------------------------"""
class LikeView(LoginRequiredMixin, generic.View):
    model = Like

    def post(self, request):
        post_id = request.POST.get('id')
        post = Post.objects.get(id=post_id)
        like = Like(user=self.request.user,post=post)
        like.save()
        like_count = Like.objects.filter(post=post).count()
        data = {'message': '『いいね』しました',
                'like_count': like_count}
        return JsonResponse(data)

"""------------------フォロー---------------------------------------------------------------------"""
@login_required
def follow_view(request, *args, **kwargs):

    try:
        follower = CustomUser.objects.get(username=request.user.username)
        following = CustomUser.objects.get(username=kwargs['username'])
    except CustomUser.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['username']))
        return HttpResponseRedirect(reverse_lazy('pento_app:index'))

    if follower == following:
        messages.warning(request, '自分自身はフォローできません')
    else:
        _, created = Connection.objects.get_or_create(follower=follower, following=following)

        if (created):
            messages.success(request, '{}をフォローしました'.format(following.username))
        else:
            messages.warning(request, 'あなたはすでに{}をフォローしています'.format(following.username))

    return HttpResponseRedirect(reverse_lazy('pento_app:detail', kwargs={'username': following.username}))

"""------------------フォロー解除-----------------------------------------------------------------"""
@login_required
def unfollow_view(request, *args, **kwargs):
    
    try:
        follower = CustomUser.objects.get(username=request.user.username)
        following = CustomUser.objects.get(username=kwargs['username'])
        if follower == following:
            messages.warning(request, '自分自身のフォローを外せません')
        else:
            unfollow = Connection.objects.get(follower=follower, following=following)
            unfollow.delete()
            messages.success(request, 'あなたは{}のフォローを外しました'.format(following.username))
    except CustomUser.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['username']))
        return HttpResponseRedirect(reverse_lazy('pento_app:index'))
    except Connection.DoesNotExist:
        messages.warning(request, 'あなたは{0}をフォローしませんでした'.format(following.username))

    return HttpResponseRedirect(reverse_lazy('pento_app:detail', kwargs={'username': following.username}))


"""------------------他ユーザーからのアクセスを制限------------------------------------------------"""
class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.username == self.kwargs['username'] or user.is_superuser

"""------------------退会機能----------------------------------------------------------------------"""
class UserDeleteView(OnlyYouMixin, generic.DeleteView):
    template_name = "delete.html"
    success_url = reverse_lazy("account_login")
    model = CustomUser
    slug_field = 'username'
    slug_url_kwarg = 'username'

"""------------------ユーザー詳細設定---------------------------------------------------------------"""
class SettingListView(TemplateView):
    template_name = "settings.html"


edit = ProfileEdit.as_view()
detail = ProifileDetail.as_view()
index = IndexView.as_view()
create = CreateView.as_view()
delete = DeleteView.as_view()
settings = SettingListView.as_view()
userdelete = UserDeleteView.as_view()
like = LikeView.as_view()

pento_app/templates/Top.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'Top.css' %}">

<div class="container">

    <!-- サイドメニュー全般 -->
    <div class="sidemenu">

        <!-- アイコン画像 -->
        <div class="circle-image">
            <img src="{% if user.thumbnail %}{{ user.thumbnail.url }}{% else %}{% static 'no_photo.png' %}{% endif %}" width="200" height="200" class="rounded-circle post-photo">
        </div>

        <!-- サイドメニューリスト -->
        <ul class="menu_list">
            <li>
                <a href="{% url 'pento_app:index' %}"><p>タイムライン</p></a>
            </li>
            <li>
                <a href="{% url 'pento_app:detail' user.username %}"><p>プロフィール</p></a>
            </li>
            <li>
                <a href="{% url 'pento_app:settings' %}"><p>ユーザー詳細設定</p></a>
            </li>
            <li>
                <a href="{% url 'account_logout' %}"><p>ログアウト</p></a>
            </li>
        </ul>
    </div>

    <!-- つぶやきライン -->
    <div class="Top_contents">
        {% block about_content %}
            
        {% endblock about_content %}
    </div>
    
</div>


{% endblock content %}

pento_app/templates/_form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'sign_up_in.css' %}"> 

<form method="post">
    {% csrf_token %}
<div class="form_content">
    {{ form.as_p }}
    <input type="submit" value="{{ submit_label }}" />
</div>
</form>
    

pento_app/templates/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'header.css' %}">  
    <link rel="stylesheet" type="text/css" href="{% static 'footer.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    {% block Title %}<title>PENTO-ARTS</title>{% endblock Title %}

    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>  

</head>

<body>

    <!-- Header Start -->
    <header class="site-header">
      <div class="wrapper site-header__wrapper">
        <h2 class="brand">PENTO-ARTS</h2>
      </div>
    </header>
    <!-- Header End -->
  
{% block content %}
{% endblock content %}

<footer id="footer01" class="footer outer-block">
  
  <p class="copyright">
    COPYRIGHT © Yoshida Takeshi. All rights Reserved.
  </p>
</footer>

</body>
<script>
  $.ajaxSetup({
    beforeSend: function (xhr, settings) {
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
      }
    }
  });
  $(document).on("click", ".post-like", function () {
    var id = $(this).data('id');
    $.ajax({
      type: "post",
      url: '{% url "pento_app:like" %}',
      data: {
        id: id,
        csrfmiddlewaretoken: $("#csrfmiddlewaretoken").val()
      },
      success: function (data) {
        $("#post-like-" + id).removeClass("post-like text-info").addClass("post-liked disabled text-secondary");
        var like_count = data["like_count"]
        $("#like-count-" + id).html(like_count);
        alert(data["message"])
      }
    });
  });
</script>


</html>

pento_app/templates/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'delete.css' %}">

<div class="content">
    <section class="del">
        <div class="del-body">
          <div class="container">
            <h1>退会画面</h1>
          </div>
        </div>
      </section>
      
      <form role="form" method="post">
        {% csrf_token %}
        <p>あなたのアカウント「@{{ user.username }}」を、本当に削除してもよろしいですか？</p>
      
        <button type="submit" class="button is-danger">削除</button>
        <a href="javascript:void(0);" onclick="window.history.back();" class="button is-text">キャンセル</a>
      </form>
</div>

{% endblock content %}

pento_app/templates/detail.html
{% extends 'Top.html' %}
{% load static %}

{% block Title %}<title>PENTO-ARTS | プロフィール</title>{% endblock Title %}

{% block about_content %}

    <link rel="stylesheet" href="{% static 'profile_detail.css' %}">

    <div class="form-content">

        {% if messages %}
        <ul>
            {% for message in messages %}
                <li class="message_fontcolor">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <h1>{{ customuser.username }}</h1>
        <p class="mt-5"><img src="{% if customuser.thumbnail %}{{ customuser.thumbnail.url }}{% else %}{% static 'no_photo.png' %}{% endif %}" class="rouded-circle profile-photo"></p>
        <p class="mt-5">{% if customuser.description %}{{ customuser.description | linebreaks }}{% else %}本文はありません{% endif %}</p>
    </div>

    <div class="button_field">

        {% if user.username == username %}
            <a href="{% url 'pento_app:edit' username %}" class="btn btn-info">プロフィール編集</a>
        {% elif connected %}
            <a href="{% url 'pento_app:unfollow' username %}" class="btn btn-dark">フォロー解除</a>
        {% else %}
            <a href="{% url 'pento_app:follow' username %}" class="btn btn-light">フォロー</a>
        {% endif %}

    </div>

    <div class="follow_count">
        <ul>
            <li>
                <p>フォロー数</p><h2>{{ following }}</h2>
            </li>
            <li>
                <p>フォロワー数</p><h2>{{ follower }}</h2>
            </li>
        </ul>
    </div>
    

{% endblock about_content %}

pento_app/templates/edit.html
{% extends 'Top.html' %}
{% load static %}
{% load bootstrap4 %}

{% block Title %}<title>PENTO-ARTS | プロフィール編集</title>{% endblock Title %}

{% block about_content %}

    <link rel="stylesheet" href="{% static 'edit.css' %}">

    <div class="container">
        <div class="profile_edit">
            <h1 class="mb-4">プロフィール</h1>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li class="message_fontcolor">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="card-body">
                <form method="POST" action="edit" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button class="btn btn-info btn-block" type="submit">保存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock about_content %}

pento_app/templates/index.html
{% extends 'Top.html' %}
{% load static %}

{% block Title %}<title>PENTO-ARTS | タイムライン</title>{% endblock Title %}

{% block about_content %}

<link rel="stylesheet" href="{% static 'style2.css' %}">


<div class="card mb-5 text-left" id="overall">

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li class="message_fontcolor">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="overall">
        <div class="card-body">
            <div class="row">

                <div class="col-2">
                    <img src="{% if user.thumbnail %}{{ user.thumbnail.url }}{% else %}{% static 'no_photo.png' %}{% endif %}" width="80" height="80" class="rounded-circle post-photo">
                </div>

                <div class="col-10">
                    <form method="POST" action="{% url 'pento_app:create' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea class="form-control" id="exampleFormControlTextarea1" name="text" rows="3" placeholder="何かつぶやいてみましょう！"></textarea>
                        </div>
                        <div class="form-group mt-1">
                            <!--※イラスト投稿機能は一旦保留
                                <label for="file">画像アップロード</label>
                                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="photo">
                            -->
                        </div>
                        <button class="btn btn-info btn-block" type="submit">投稿</button>
                    </form>　　
                </div>
            </div>
        </div>
    </div>
</div>

{% for post in object_list %}

<div class="card mb-5 text-left">

    <div class="card-body">
        <div class="row">
            <div class="col-1">
                <a href="{% url 'pento_app:detail' post.author.username %}"><img src="{% if post.author.thumbnail %}{{ post.author.thumbnail.url }}{% else %}{% static 'no_photo.png' %}{% endif %}" class="rounded-circle profile-post-photo"></a>
            </div>

            <div class="col-10 ml-3">
                <a href="{% url 'pento_app:detail' post.author.username %}" class="text-secondary">{{ post.author }}</a><br>
                <small class="text-muted">{{ post.created_at | date:'n月j日H時i分' }}</small>
            </div>
        </div>
        <p class="card-text mt-2">{{ post.text | linebreaks }}</p>

        <button class="btn btn-link p-0 {% if user in post.get_like %}disabled post-liked text-secondary{% else %}post-like text-info{% endif %}" id="post-like-{{ post.id }}" data-id="{{ post.id }}">
            いいね
        </button>
        <span class="badge badge-info" id="like-count-{{ post.id }}">{% if post.get_like %}{{ post.get_like | length }}{% endif %}</span>
    
        {% if post.author.id == user.id %}
            <form method="POST" action="{% url 'pento_app:delete' post.id %}" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-link text-info p-0 ml-3" type="submit" onclick='return confirm("この投稿を本当に削除しますか？");'>削除</button>
            </form>
        {% endif %}
        
    </div>

    {% if post.post_photo %}
        <a href="{{ post.post_photo.url }}" data-lightbox="{{ post.post_photo.url }}"><img class="card-img-bottom" src="{{ post.post_photo.url }}" alt="Card image cap" ></a>
    {% endif %}

</div>
{% endfor %}

<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link text-info" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item disabled">
                    <span class="page-link">{{ i }}</span>
                </li>
            {% else %}
            <li class="page-item">
                <a class="page-link text-info" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link text-info" href="?page={{ page_obj.next_page_number }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">&raquo;</span>
            </li>
        {% endif %}
    </ul>
</nav>

{% endblock about_content %}

pento_app/templates/logout_message.html
{% extends "base.html" %}
{% load static }

{% block content %}

    <div class="logout_message">
        <p>ログアウトしました。作業お疲れ様です。</p>
        <a href="{% url 'account' %}"></a>
    </div>

{% endblock content %}

pento_app/templates/settings.html
{% extends "Top.html" %}
{% load static %}

{% block about_content %}

<link rel="stylesheet" href="{% static 'settings.css' %}">

<div class="setting-list">
    <ul>
        {% if user.is_authenticated %}
            <a href="{% url 'pento_app:userdelete' user.username %}"><li>退会する</li></a>
        {% endif %}
    </ul>
</div>
            
{% endblock about_content %}

pento_app/templates/upload.html
{% extends 'Top.html' %}
{% load static %}

{% block header_menu %}
<!--ログイン後はメニューなし-->
{% endblock header_menu %}

{% block about_content %}

<link rel="stylesheet" type="text/css" href="{% static 'upload.css' %}">
<script type="text/javascript" src="{% static 'upload.js' %}"></script>

<div class="upload">

    <h3 class="upload_title">イラスト投稿</h3>

    <div class="upload_menu">

        <form enctype="multipart/form-data" action="{% url 'pento_app:upload' %}" method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="投稿">
            {{ form.media }}
        </form>

        <img id="file-preview">

    </div>

    <a href="{% url 'pento_app:timeline' %}"><p>ホームへ戻る</p></a>

</div>

{% endblock about_content %}